spring:
  config:
    import: optional:application-secret.yml
  profiles:
    active: local  # ??? local(H2) ??
    include: secret  # JWT 설정 로드

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace
